<a href="https://colab.research.google.com/github/coddingyun/pytorch/blob/ch2/Bookstudy_ch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 텐서 조작하기

##1. 벡터, 행렬, 그리고 텐서

-2D tensor : (Batchsize, dim)

-3D tensor : (Batchsize, width, height) -> 비전분야

-3D tensor : (Batchsize, length, dim) -> NLD 분야

##2. 넘파이로 텐서 만들기 (벡터와 행렬 만들기)

In [ ]:
import numpy as np

###1. 1D with Numpy

In [ ]:
t=np.array([0.,1.,2.,3.,4.,5.,6.])
#List를 생서해서 np.array로 1차원 array로 변환함
print(t)

print('Rank of t: ',t.ndim) #차원
print('Shape of t: ', t.shape) #크기 (7,) = (1,7) =(1x7)

[0. 1. 2. 3. 4. 5. 6.]
Rank of t:  1
Shape of t:  (7,)


In [ ]:
print('t[0], t[1], t[-1] = ', t[0],t[1],t[-1])
print('t[2:5], t[4:-1] = ', t[2:5],t[4:-1])
print('t[:2], t[3:] = ', t[:2],t[3:])

t[0], t[1], t[-1] =  0.0 1.0 6.0
t[2:5], t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2], t[3:] =  [0. 1.] [3. 4. 5. 6.]


###2. 2D with Numpy

In [ ]:
t=np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.], [10.,11.,12.]])
print(t)

print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank  of t:  2
Shape of t:  (4, 3)


##3. 파이토치 텐서 선언하기

In [ ]:
import torch

###1. 1D with PyTorch

In [ ]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])


In [ ]:
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


###2. 2D with PyTorch

In [ ]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

print(t.dim())
print(t.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])


In [ ]:
print(t[:, 1]) #두번째 차원의 첫번째 것을 모두 가져옴
print(t[:, 1].size())

print(t[:,:-1]) #두번째 차원의 맨마지막을 제외하고 모두 가져옴

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


###3. 브로드캐스팅(Broadcasting)

자동으로 크기를 맞춰서 연산을 수행하게 만드는 기능

In [ ]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2) # 둘다 크기가 (1,2) 이므로 문제 없이 연산 수행

tensor([[5., 5.]])


In [ ]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [ ]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # [[1, 2], [1, 2]]
m2 = torch.FloatTensor([[3], [4]]) # [[3, 3], [4, 4]]
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


###4. 자주 사용되는 기능들

1) 행렬 곱셈과 곱셈의 차이

In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1
#.matmul() : 행렬곱셈

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape) # [[1, 1], [2, 2]]
print(m1 * m2) # 2 x 2
print(m1.mul(m2))
# * or .mul() : 원소끼리 곱셈

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


2) 평균

In [ ]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())

tensor(2.5000)


In [ ]:
print(t.mean(dim=0))
#dim=0: 첫번째 차원
#t.mean(dim=0): 첫번째 차원(행) 제거

tensor([2., 3.])


In [ ]:
print(t.mean(dim=1))
#t.mean(dim=1): 두번째 차원(열) 제거

tensor([1.5000, 3.5000])


In [ ]:
print(t.mean(dim=-1))
#t.mean(dim=-1): 마지막 차원(열) 제거

tensor([1.5000, 3.5000])


3) 덧셈

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


4) 최대(Max)와 아그맥스(ArgMax)

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max()) #max
print(t.max(dim=0)) #max, argmax

print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [ ]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


##4. 뷰(View)
원소의 수를 유지하면서 텐서의 크기 변경

In [ ]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


###1. 3차원 텐서에서 2차원 텐서로 변경

In [ ]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)
#Rule 1. view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 합니다.
#Rule 2. 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추합니다.

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


###2. 3차원 텐서의 크기 변경

In [ ]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


##5. 스퀴즈
차원이 1인 경우에 제거

In [ ]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().shape)

torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


##6. 언스퀴즈
특정 위치에 1인 차원을 추가

In [ ]:
ft=torch.Tensor([0,1,2])
print(ft.unsqueeze(0)) # 0은 첫번째 차원 의미
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


##7. 타입캐스팅

텐서에는 자료형이 존재

torch.FloatTensor : 32비트의 부동소수점

torch.LongTensor : 64비트의 부호 있는 정수

자료형을 변환하는 것을 타입캐스팅이라고 한다.

In [ ]:
lt=torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [ ]:
bt=torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


##8. 연결하기(concatenate)

In [ ]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])
print(torch.cat([x,y], dim=0)) #dim=0:첫번째차원 늘리기
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


##9. 스택킹(Stacking)

In [ ]:
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])
print(torch.stack([x,y,z]))
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)], dim=0)) #차원 하나 넣고, 첫번째 차원 늘리기

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
print(torch.stack([x,y,z], dim=1)) # 두번째 차원이 증가하도록 쌓기

tensor([[1., 2., 3.],
        [4., 5., 6.]])


##10. ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서

In [ ]:
x=torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


##11. In-place Operation (덮어쓰기 연산)

In [ ]:
x=torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2.))
print(x)

print(x.mul_(2.)) #덮어쓰기
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


# 파이썬 클래스

##1. 함수(function)로 덧셈기 구현하기

In [ ]:
result=0
def add(num):
    global result
    result += num
    return result
print(add(3))
print(add(4))

3
7


##2. 클래스(class)로 덧셈기 구현하기

In [ ]:
class Calculator:
  def __init__(self): #객체 셍성시 호출될때 실행되는 초기화 함수. 생성자
    self.result=0
  def add(self, num):
    self.result += num
    return self.result

cal1= Calculator()
cal2= Calculator()

print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10
